<?php
echo "<table class='toplineback'>";
echo "<tr>";
echo "<td>";
echo "</td>";
echo "</tr>";
echo "</table>";

echo "<table class='topline'>";
echo "<tr>";
echo "<td>";
echo "<a href='$Wemakeli_Web_Root/about/'>";
echo "<img src='$Wemakeli_Web_Root/library/image/common/websitelogo.png' class='websitetitleimage' title='$websitename' alt='$websitename'></img>";
echo "</a>";
echo "<a href='$Wemakeli_Web_Root'>";
echo "<input name='主页' type='button' title='主页' value='主页'>";
echo "</a>";
echo "<a href='$Wemakeli_Web_Root/video/'>";
echo "<input name='视频' type='button' title='视频' value='视频'>";
echo "</a>";
echo "<a href='$Wemakeli_Web_Root/audio/'>";
echo "<input name='音频' type='button' title='音频' value='音频'>";
echo "</a>";
echo "<a href='$Wemakeli_Web_Root/read/'>";
echo "<input name='专栏' type='button' title='专栏' value='专栏'>";
echo "</a>";
echo "<a href='$Wemakeli_Web_Root/file/'>";
echo "<input name='文件' type='button' title='文件' value='文件'>";
echo "</a>";
echo "</td>";
echo "</tr>";
echo "</table>";

echo "<table class='toplinelogin'>";
echo "<tr>";
echo "<td>";
if (isset($_COOKIE["username"])){
  $username=$_COOKIE['username'];
  $useruid=$_COOKIE['useruid'];
  echo "<a href='$Wemakeli_Web_Root/user/?useruid=$useruid'>";
  echo "<img src='$Wemakeli_Web_Root/user/$useruid/userimage.png' class='toplineuserimage' title='$username' alt='$username'></img>";
  echo "<echo class=toplineecho>$username</echo>";
  echo "</a>";
  echo "<a href='$Wemakeli_Web_Root/accout/message.php'>";
  echo "<input name='消息' type='button' class='topline_message' title='消息' value='消息'>";
  echo "</a>";
  echo "<a href='$Wemakeli_Web_Root/accout/rtmessage.php'>";
  echo "<input name='动态' type='button' class='topline_rtmessage' title='动态' value='动态'>";
  echo "</a>";
  echo "<a href='$Wemakeli_Web_Root/accout/favorite.php'>";
  echo "<input name='收藏' type='button' class='topline_favorite' title='收藏' value='收藏'>";
  echo "</a>";
  echo "<a href='$Wemakeli_Web_Root/accout/history.php'>";
  echo "<input name='历史' type='button' class='topline_history' title='历史' value='历史'>";
  echo "</a>";
  echo "<a href='$Wemakeli_Web_Root/accout/workcenter.php'>";
  echo "<input name='创作中心' type='button' class='topline_workcenter' title='创作中心' value='创作中心'>";
  echo "</a>";
  echo "<a href='$Wemakeli_Web_Root/accout/accoutcenter.php'>";
  echo "<input name='用户中心' type='button' class='topline_accoutcenter' title='用户中心' value='用户中心'>";
  echo "</a>";
  echo "<a href='$Wemakeli_Web_Root/accout/uploadvideo.php'>";
  echo "<input name='投稿' type='button' class='topline_workcenter' title='投稿' value='投稿'>";
  echo "</a>";
  goto ntxlgnbr;
}else{
  echo "用户未登录";
  echo "<a href='$Wemakeli_Web_Root/accout/accoutlogin.php'>";
  echo "<input name='登录' type='button' class='topline_login' title='登录' value='登录'>";
  echo "</a>";
  goto ntxlgnbr;
}
ntxlgnbr:
echo "</td>";
echo "</tr>";
echo "</table>";

echo "<table class='leftline'>";
echo "<tr>";
echo "<td>";
echo "<a href='" . $websiteaddress . "/video/wv-1/'>";
echo "<img src='$Wemakeli_Web_Root/library/image/videotop/wv-1.png' class='videologo'></img>";
echo "<div class='videologotitle'>Bad Apple!!</div>";
echo "</a>";
echo "<a href='" . $websiteaddress . "/video/wv0/'>";
echo "<img src='$Wemakeli_Web_Root/library/image/videotop/wv0.png' class='videologo'></img>";
echo "<div class='videologotitle'>测试Danmakuplayer</div>";
echo "</a>";
echo "<a href='" . $websiteaddress . "/video/wv1/'>";
echo "<img src='$Wemakeli_Web_Root/library/image/videotop/wv4.png' class='videologo'></img>";
echo "<div class='videologotitle'>MOPEMOPE</div>";
echo "</a>";
echo "<a href='" . $websiteaddress . "/video/wv2/'>";
echo "<img src='$Wemakeli_Web_Root/library/image/videotop/wv3.png' class='videologo'></img>";
echo "<div class='videologotitle'>Sad Machine</div>";
echo "</a>";
echo "<a href='" . $websiteaddress . "/read/wr0/'>";
echo "<img src='$Wemakeli_Web_Root/library/image/videotop/wr0.png' class='videologo'></img>";
echo "<div class='videologotitle'>希灵帝国-远瞳</div>";
echo "</a>";
echo "<a href='" . $websiteaddress . "/read/wr1/'>";
echo "<img src='$Wemakeli_Web_Root/library/image/videotop/wr1.png' class='videologo'></img>";
echo "<div class='videologotitle'>Untitled</div>";
echo "</a>";
echo "<a href='" . $websiteaddress . "/audio/wa0/'>";
echo "<img src='$Wemakeli_Web_Root/library/image/videotop/wa0.png' class='videologo'></img>";
echo "<div class='videologotitle'>Music0 00003</div>";
echo "</a>";
echo "<a href='" . $websiteaddress . "/audio/wa1/'>";
echo "<img src='$Wemakeli_Web_Root/library/image/videotop/wa1.png' class='videologo'></img>";
echo "<div class='videologotitle'>Music24 00012</div>";
echo "</a>";
echo "<a href='" . $websiteaddress . "/audio/wa2/'>";
echo "<img src='$Wemakeli_Web_Root/library/image/videotop/wa2.png' class='videologo'></img>";
echo "<div class='videologotitle'>Music29 00005</div>";
echo "</a>";
echo "</a>";
echo "</td>";
echo "</tr>";
echo "</table>";

?>