__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   "render": function() { return /* binding */ render; },
/* harmony export */   "staticRenderFns": function() { return /* binding */ staticRenderFns; }
/* harmony export */ });
var render = function () {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _c('transition',{attrs:{"name":"bili-word-box"}},[_c('div',{directives:[{name:"show",rawName:"v-show",value:(_vm.visible),expression:"visible"}],attrs:{"id":"bili-wordverify-box"},on:{"touchmove":_vm.touchMove}},[_c('div',{staticClass:"bili-wordverify-bg"}),_vm._v(" "),_c('div',{ref:"wrapper",staticClass:"bili-wordverify-wrapper"},[_c('div',{staticClass:"bili-wordverify-container",on:{"click":function($event){$event.stopPropagation();}}},[_c('i',{staticClass:"pop-close",on:{"click":function($event){return _vm.close('cancel')}}}),_vm._v(" "),_c('div',{style:({ visibility: _vm.showContent ? 'visible' : 'hidden' })},[_c('div',{staticClass:"bili-word-bg-wrapper"},[_c('div',{staticClass:"question-group"},[_c('h4',[_vm._v("请回答社区礼仪问题，完成验证")]),_vm._v(" "),_c('p',{domProps:{"innerHTML":_vm._s(this.questionTxt)}})]),_vm._v(" "),_c('img',{staticStyle:{"position":"absolute","left":"0"},attrs:{"width":_vm.isSmallScreen ? '260px' : '256px',"height":_vm.isSmallScreen ? '157.5px' : '144px',"src":_vm.backgroundImageUrl},on:{"load":_vm.backgroundOnload}}),_vm._v(" "),_c('div',{ref:"bg",class:_vm.isSmallScreen ? 'bili-word-small-bg' : 'bili-word-bg',on:{"click":_vm.getMove}}),_vm._v(" "),_c('div',{staticClass:"clean-group",on:{"click":_vm.resetCapture}},[_c('span',[_vm._v("清空")])])]),_vm._v(" "),_c('div',{staticClass:"button-wrapper"},[_c('div',{staticClass:"button-common",on:{"click":_vm.getCaptcha}},[_vm._v("换一题")]),_vm._v(" "),(!_vm.isValidate)?_c('div',{staticClass:"button-active",class:this.biliwordParams.theme,on:{"click":_vm.validateCapture}},[_vm._v("\n              提交\n            ")]):_c('div',{staticClass:"button-active unable"},[_vm._v("正在提交")])])]),_vm._v(" "),(!_vm.showContent)?_c('div',{staticClass:"warning-group"},[(_vm.showFailContent)?[_c('Img',{attrs:{"type":"fail"}}),_vm._v(" "),_c('div',{staticClass:"warning-text"},[_vm._v(_vm._s(_vm.failText))]),_vm._v(" "),_c('div',{staticClass:"button-active",class:this.biliwordParams.theme,on:{"click":_vm.getCaptcha}},[_vm._v("\n              重试\n            ")])]:[_c('Img',{attrs:{"type":"loading"}}),_vm._v(" "),_c('div',{staticClass:"warning-text"},[_vm._v("努力加载中...")])]],2):_vm._e()])])])])}
var staticRenderFns = []


